step_time: 0.001

initial_position:
  x: 5.0
  y: 5.0
  theta: 0.9
  v: 0.0
  omega: 0.0

map:
  x: 20.0
  y: 20.0

model:
  L: 0.1
  max_a: 10
  max_v: 5
  lf: 0.1

map_name: "map/spline.csv"

look_ahead: 5

ds: 0.01

visual: true

ref_ahead: 32

MPC:
  N: 30
  dt: 0.01
  desire_v: 2
  input:
    ul: 0.001
    ur: 0.001
  state:
    x: 1
    y: 1
    theta: 0.1
    v: 10
    omega: 10