step_time: 0.001

ts: 0.04

is_ai: False # ai or RK4

is_print: False # print or not

initial_position:
  x: -1.5
  y: -0.15
  theta: 0.9
  v: 0.0
  omega: 0.0

map:
  x: 20.0
  y: 20.0

model:
  L: 0.308
  max_a: 2
  max_v: 1

map_name: "map/spline.csv"

look_ahead: 5

ds: 0.01

visual: true

controller: 'mpc'  # ['mpc', 'purepursuit']

ref_ahead: 20

MPC:
  N: 20
  dt: 0.01
  desire_v: 0.2
  input:
    ul: 0.001
    ur: 0.001
  state:
    x: 100
    y: 100
    theta: 0.3
    v: 10
    omega: 0.01